package club.renxl.www.management.school.user.dao.domain;

public class College {
    /**  */
    private Short coid;

    /**  */
    private String name;

    /**  */
    private Integer provinceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.coid
     *
     * @return the value of college.coid
     *
     * @mbggenerated
     */
    public Short getCoid() {
        return coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.coid
     *
     * @param coid the value for college.coid
     *
     * @mbggenerated
     */
    public void setCoid(Short coid) {
        this.coid = coid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.name
     *
     * @return the value of college.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.name
     *
     * @param name the value for college.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.provinceID
     *
     * @return the value of college.provinceID
     *
     * @mbggenerated
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.provinceID
     *
     * @param provinceid the value for college.provinceID
     *
     * @mbggenerated
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }
}