package club.renxl.www.management.school.user.dao.domain;

import java.util.Date;

public class Comment {
    /**  */
    private Long id;

    /** 评论或回复。舍弃回复表 */
    private Long pid;

    /** 文章id */
    private Long topicId;

    /** 1为课程，2为集会，3为商品 */
    private Byte topicType;

    /** 评论者id，一般为会员表的id */
    private Long fromUid;

    /** 冗余用户昵称 */
    private String nickname;

    /** 冗余用户头像 */
    private String thumbImg;

    /** 是否置顶评论，1为置顶，0为不置顶 */
    private Byte isTop;

    /** 是否为热评，1为热评 */
    private Byte isHot;

    /** 评论回复被点赞的次数 */
    private Integer likeNum;

    /** 评论回复被回复的次数 */
    private Integer replyNum;

    /** 是否回复0评论1有回复 */
    private Byte isReply;

    /** 评论状态，-1为删除，0为待审核，1为已发布 */
    private Byte status;

    /** 创建时间 */
    private Date createTime;

    /**  */
    private Long toUid;

    /**  */
    private String toNickname;

    /**  */
    private String toThumbImg;

    /** 评论内容 */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.id
     *
     * @return the value of school_comment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.id
     *
     * @param id the value for school_comment.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.pid
     *
     * @return the value of school_comment.pid
     *
     * @mbggenerated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.pid
     *
     * @param pid the value for school_comment.pid
     *
     * @mbggenerated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.topic_id
     *
     * @return the value of school_comment.topic_id
     *
     * @mbggenerated
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.topic_id
     *
     * @param topicId the value for school_comment.topic_id
     *
     * @mbggenerated
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.topic_type
     *
     * @return the value of school_comment.topic_type
     *
     * @mbggenerated
     */
    public Byte getTopicType() {
        return topicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.topic_type
     *
     * @param topicType the value for school_comment.topic_type
     *
     * @mbggenerated
     */
    public void setTopicType(Byte topicType) {
        this.topicType = topicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.from_uid
     *
     * @return the value of school_comment.from_uid
     *
     * @mbggenerated
     */
    public Long getFromUid() {
        return fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.from_uid
     *
     * @param fromUid the value for school_comment.from_uid
     *
     * @mbggenerated
     */
    public void setFromUid(Long fromUid) {
        this.fromUid = fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.nickname
     *
     * @return the value of school_comment.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.nickname
     *
     * @param nickname the value for school_comment.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.thumb_img
     *
     * @return the value of school_comment.thumb_img
     *
     * @mbggenerated
     */
    public String getThumbImg() {
        return thumbImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.thumb_img
     *
     * @param thumbImg the value for school_comment.thumb_img
     *
     * @mbggenerated
     */
    public void setThumbImg(String thumbImg) {
        this.thumbImg = thumbImg == null ? null : thumbImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.is_top
     *
     * @return the value of school_comment.is_top
     *
     * @mbggenerated
     */
    public Byte getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.is_top
     *
     * @param isTop the value for school_comment.is_top
     *
     * @mbggenerated
     */
    public void setIsTop(Byte isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.is_hot
     *
     * @return the value of school_comment.is_hot
     *
     * @mbggenerated
     */
    public Byte getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.is_hot
     *
     * @param isHot the value for school_comment.is_hot
     *
     * @mbggenerated
     */
    public void setIsHot(Byte isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.like_num
     *
     * @return the value of school_comment.like_num
     *
     * @mbggenerated
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.like_num
     *
     * @param likeNum the value for school_comment.like_num
     *
     * @mbggenerated
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.reply_num
     *
     * @return the value of school_comment.reply_num
     *
     * @mbggenerated
     */
    public Integer getReplyNum() {
        return replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.reply_num
     *
     * @param replyNum the value for school_comment.reply_num
     *
     * @mbggenerated
     */
    public void setReplyNum(Integer replyNum) {
        this.replyNum = replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.is_reply
     *
     * @return the value of school_comment.is_reply
     *
     * @mbggenerated
     */
    public Byte getIsReply() {
        return isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.is_reply
     *
     * @param isReply the value for school_comment.is_reply
     *
     * @mbggenerated
     */
    public void setIsReply(Byte isReply) {
        this.isReply = isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.status
     *
     * @return the value of school_comment.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.status
     *
     * @param status the value for school_comment.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.create_time
     *
     * @return the value of school_comment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.create_time
     *
     * @param createTime the value for school_comment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.to_uid
     *
     * @return the value of school_comment.to_uid
     *
     * @mbggenerated
     */
    public Long getToUid() {
        return toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.to_uid
     *
     * @param toUid the value for school_comment.to_uid
     *
     * @mbggenerated
     */
    public void setToUid(Long toUid) {
        this.toUid = toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.to_nickname
     *
     * @return the value of school_comment.to_nickname
     *
     * @mbggenerated
     */
    public String getToNickname() {
        return toNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.to_nickname
     *
     * @param toNickname the value for school_comment.to_nickname
     *
     * @mbggenerated
     */
    public void setToNickname(String toNickname) {
        this.toNickname = toNickname == null ? null : toNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.to_thumb_img
     *
     * @return the value of school_comment.to_thumb_img
     *
     * @mbggenerated
     */
    public String getToThumbImg() {
        return toThumbImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.to_thumb_img
     *
     * @param toThumbImg the value for school_comment.to_thumb_img
     *
     * @mbggenerated
     */
    public void setToThumbImg(String toThumbImg) {
        this.toThumbImg = toThumbImg == null ? null : toThumbImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_comment.content
     *
     * @return the value of school_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_comment.content
     *
     * @param content the value for school_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}